---
title: "UTI-AB"
author: "Yiziying Chen"
date: "2/26/2019"
output: html_document
---

```{r warning=FALSE}
library(stats4)
setwd( "/Users/yiziyingchen/Desktop/Townsend/UTI")
library("readxl")
uti.AB =  read_excel("UTI.xlsx", sheet = 2)
uti.AB$iso = uti.AB$Isolates_AB
uti.AB$resis = uti.AB$Resistance_AB
uti.AB$freq = uti.AB$resis/uti.AB$iso

t = seq(0,16,1)

d1 = c()
d2 = c()
c3 = c()
d4 = c()
d5 = c()
d.mean = c()
theta.m <- c()
set.seed(111)
for (i in 1:1000){
  d1 <- rnorm(18, 0.989, 0.006)
  d2 <- rnorm(18, 0.964, 0.008)
  d3 <- rnorm(18, 0.974, 0.013)
  d4 <- rnorm(18, 0.985, 0.005)
  d5 <- rnorm(18, 0.982, 0.007)
  d.mean <- (d1+d2+d3+d4+d5)/5
  theta.m <- c(theta.m, d.mean)
}
ab.theta <- mean(theta.m)

ab.k <- uti.AB$resis
ab.n <- uti.AB$iso
at <- sum(uti.AB$consump)/17
ab.at <- rep(at, 17)
```

```{r}
#12.9/10K PY AT 1998
#18.4/10k py at 2011
y = c(12.9*10^-4, 18.4*10^-4)
x = c(1998, 2011)
fit = lm(y ~ x)
year = c(2000:2016)
uti = predict(fit,data.frame(x = year))
uti.inc = max(uti)
```

```{r eval = FALSE}
#use optim
ll <- function(param){
  r0 = param[1]
  rho = param[2]
  R <- dbinom(ab.k, ab.n, exp((rho*uti.AB$consump+ab.theta -1)*t)/(1/r0-1+exp((rho*uti.AB$consump + ab.theta-1)*t)))
  -sum(log(R))
}
ab.rho = optim(par = c(0.03,0), ll)$par[2]

ab.r0 = optim(par = c(0.03,0), ll)$par[1]
ab.rt <- exp((ab.rho*uti.AB$consump+ab.theta -1)*t)/(1/ab.r0-1+exp((ab.rho*uti.AB$consump + ab.theta-1)*t))
cbind(ab.rho, ab.r0)
plot(ab.rt,  ylab = "r(t)", main = "Fitted r(t)-UTI.AB",x = c(2000:2016),type = "l")
data.frame(ab.rt, uti.AB$freq)
```

```{r}
consump <- lm(consump ~ t, data = uti.AB)
#2015 to 2019 projection
t1 <- seq(17,20,1)
consump.trend1 <- sapply(t1, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend1 <- ab.rho*consump.trend1 + ab.theta -1
rt.trend1 <- exp(m.trend1*t1) / (1/ab.r0 -1 + exp(m.trend1*t1))

#2020 to 2024 projection
t2 <- seq(21,25,1)
consump.trend2 <- sapply(t2, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend2 <- ab.rho*consump.trend2 + ab.theta-1
  ##without stewarship
  rt.trend2 <- exp(m.trend2*t2) / (1/ab.r0 -1 + exp(m.trend2*t2))
  ##with stewarship
  t2.1 <- c()
  c.trend2.1 <- c()
  rt.trend2.1 <- c()
  rt.t2.1<- c()
  for (i in 1:5){
    t2.1[i] <- (1-(0.52/5)*i)*consump.trend2[1]
    c.trend2.1 <- c(c.trend2.1, t2.1[i])
}
    m.trend2.1 <- ab.rho*c.trend2.1 + ab.theta -1
    rt.trend2.1 <- exp(m.trend2.1*t2) / (1/ab.r0 -1 + exp(m.trend2.1*t2))

t2.1<- seq(1,15,1)
consump.trend2.1.1 <-summary(consump)$coefficients[2]*t2.1 + c.trend2.1[5]
m.trend2.1.1 <- ab.rho*consump.trend2.1.1 + ab.theta -1
rt.trend2.1.1 <- exp(m.trend2.1.1 * c(26:40)) / (1/ab.r0-1 + exp(m.trend2.1.1*c(26:40)))


#2025 to 2030 projection
t3 <- seq(26,30,1)
consump.trend3 <- sapply(t3, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))

  ##without stewarship
  m.trend3 <- ab.rho*consump.trend3 + ab.theta -1
  rt.trend3 <- exp(m.trend3*(t3)) / (1/ab.r0 -1 + exp(m.trend3*t3))
  ##with stewarship
  t3.1 <- c()
  c.trend3.1 <- c()
  rt.trend3.1 <- c()
  rt.t3.1 <- c()
  for (i in 1:5){
    t3.1[i] <- (1-(0.52/5)*i)*consump.trend3[1]
    c.trend3.1 <- c(c.trend3.1, t3.1[i])
}
  m.trend3.1 <- ab.rho*c.trend3.1 + ab.theta -1 
  rt.trend3.1 <- exp(m.trend3.1*t3) / (1/ab.r0 -1 + exp(m.trend3.1*t3))
  
t3.1<- seq(1,10,1)
consump.trend3.1.1 <-summary(consump)$coefficients[2]*t3.1 + c.trend3.1[5]
m.trend3.1.1 <- ab.rho*consump.trend3.1.1 + ab.theta -1
rt.trend3.1.1 <- exp(m.trend3.1.1 * c(31:40)) / (1/ab.r0-1 + exp(m.trend3.1.1*c(31:40)))

#2035 to 2040 projection
t4 <- seq(31,35,1)
consump.trend4 <- sapply(t4, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
  ##without stwership
  m.trend4 <- ab.rho*consump.trend4 + ab.theta -1
  rt.trend4 <- exp(m.trend4*t4) / (1/ab.r0 -1 + exp(m.trend4*t4))
  ##with stwership 
  t4.1 <- c()
  c.trend4.1 <- c()
for (i in 1:5){
  t4.1[i] <- (1-(0.52/5)*i)*consump.trend4[1]
  c.trend4.1 <- c(c.trend4.1, t4.1[i])
}
  m.trend4.1 <- ab.rho*c.trend4.1 + ab.theta -1
  rt.trend4.1 <- exp(m.trend4.1*t4) / (1/ab.r0 -1 + exp(m.trend4.1*t4))

t4.1<- seq(1,5,1)
consump.trend4.1.1 <-summary(consump)$coefficients[2]*t4.1 + c.trend4.1[5]
m.trend4.1.1 <- ab.rho*consump.trend4.1.1 + ab.theta -1
rt.trend4.1.1 <- exp(m.trend4.1.1 * c(36:40)) / (1/ab.r0-1 + exp(m.trend4.1.1*c(36:40)))  
  
#general without stewardship
t.g<- seq(17,40,1)
consump.trend.g<-sapply(t.g, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend.g <- ab.rho*consump.trend.g + ab.theta -1
rt.trend.g <- exp(m.trend.g*t.g) / (1/ab.r0 -1 + exp(m.trend.g*t.g))

```

```{r}
#plot overlay resisatnce frequency with/out intervension
plot(2000:2040, ylim = c(min(uti.AB$freq), max(rt.trend.g)),y = c(uti.AB$freq, rt.trend1, rt.trend2.1, rep(min(rt.trend2.1),15)), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "blue", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(uti.AB$freq), max(rt.trend.g)),y = c(uti.AB$freq, rt.trend1, rt.trend2, rt.trend3.1, rep(min(rt.trend3.1),10)), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "purple", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(uti.AB$freq), max(rt.trend.g)),y = c(uti.AB$freq, rt.trend1, rt.trend2, rt.trend3, rt.trend4.1, rep(min(rt.trend4.1),5)), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "red", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(uti.AB$freq), max(rt.trend.g)),y = c(uti.AB$freq,rt.trend.g), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship")
#text(c(2000:2040), c(ab.rt,rt.trend.g), round(c(ab.rt,rt.trend.g),2),cex=0.75, col = "dark orange")

legend(2000, 1, legend = c("without stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.8, text.font=4, bg='lightblue')
```

#Resistance frequency compare
```{r}
library(scales)
rt.compare <- function(x1, x2) percent(((max(x1) - min(x2)) / min(x2)))
#2020 intervention
inter1 <- rt.compare(rt.trend2, rt.trend2.1)
#2025 intervention
inter2 <- rt.compare(rt.trend3, rt.trend3.1)
#2030 intervention
inter3<- rt.compare(rt.trend4, rt.trend4.1)
intervention <- c(2020,2025,2030)
#5-year RF change percentage with intervention
RF_diff <- c(inter1, inter2, inter3)
#5-year end point RF
END_RF = c(min(rt.trend2.1), min(rt.trend3.1), min(rt.trend4.1))

data.frame(intervention, RF_diff)
data.frame(intervention, END_RF)
```

#resistance case difference-CROSS US
```{r}
pop = read_excel("population.xlsx", sheet = 1)
uti.ab = uti.AB$`UTI- AB`[17]
cbp.uti = mean(uti.AB$`CBP-UTI`)
#ratio of pneu contributed by PA should not be decreasing; take the last time point
in.cbp = 0.122622696
uti.inc = max(uti)
#pneu.pa =c()
#p1 = c()
#for(i in 15:40){
  #p1 = summary(m1)$coefficient[1] + summary(m1)$coefficient[2]*i
  #pneu.pa = c(pneu.pa,p1)
#}

#pneu.pa

case = c()
cn = c()
for(i in 17:40){
  cn = uti.ab*cbp.uti*pop$Population[(i-14)]*uti.inc
  case = c(case,cn)
}

c25 = rt.trend.g[9]*case[9]
c25.1 = rt.trend2.1[5]*case[9]
int.2020 = c25 - c25.1
c30 = rt.trend.g[14]*case[14]
c30.1 = rt.trend3.1[5]*case[14]
int.2025 = c30 - c30.1
c35 = rt.trend.g[19]*case[19]
c35.1 = rt.trend4.1[5]*case[19]
int.2030 = c35 - c35.1
CASE.diff = c(ceiling(int.2020), ceiling(int.2025), ceiling(int.2030))
YEAR = c(2020,2025,2030)

#5-year end point resistance cases number across US
END.CASE <- ceiling(c(c25.1, c30.1, c35.1))
NO.STEWARD = c(c25, c30, c35)

#5-year isolate case number change under intervention in US
data.frame(YEAR,  NO.STEWARD, END.CASE, CASE.diff)
```

#plot resistance cases across US
```{r}
reduc = c()
for(i in 1:5)(reduc[i] = 1-(0.52/5)*i)
c.g1 <- case[1:4]*rt.trend.g[1:4]
c.g2 <- case[1:9]*rt.trend.g[1:9]
c.g3 <- case[1:14]*rt.trend.g[1:14]
c.2020 <- reduc*case[5:9]*rt.trend2.1
c.2020.1<- rep(c.2020[5],15)
c.2025 <- reduc*case[10:14]*rt.trend3.1
c.2025.1<- rep(c.2025[5],10)
c.2030 <- reduc*case[15:19]*rt.trend4.1
c.2030.1<- rep(c.2030[5],5)


plot((case*rt.trend.g)[3:24], x = c(2019:2040), type = "l", ylim = range(0,c.2020.1,case*rt.trend.g),main = "Resistance across US from CBP prescription due to Pneumonia",yaxt = "n", ylab = "Resistance per year",  xlab = "Year")
par(new = T)
plot(c(c.g1[3:4], c.2020, c.2020.1), x = c(2019:2040), type = "l", ylim = range(0,c.2020.1, case*rt.trend.g), main = "Resistance across US from CBP prescription due to Bacteremia", ylab = "Resistance per year", yaxt = "n", xlab = "Year", col = "blue", lty = 2)
par(new = T)
plot(c(c.g2[3:9], c.2025, c.2025.1), x = c(2019:2040), type = "l", ylim = range(0,c.2020.1, case*rt.trend.g), main = "Resistance across US from CBP prescription due to Bacteremia", ylab = "Resistance per year", yaxt = "n", xlab = "Year", col = "purple", lty = 2)
par(new = T)
plot(c(c.g3[3:14], c.2030, c.2030.1), x = c(2019:2040), type = "l", ylim = range(0,c.2020.1, case*rt.trend.g), main = "Resistance across US from CBP prescription due to Bacteremia", ylab = "Resistance per year", yaxt = "n", xlab = "Year", col = "red", lty = 2)
axis(side=2, at=c(0, 100, 200, 300,400,500,600), hadj=0.8, cex.axis=0.9, las=2)
legend(2019, 150, legend = c("without stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.6, text.font=4, bg='lightblue')
```

#calculate total change of case due to intervention
```{r}
Intervention.YEAR = c(2020,2025,2030)
case.diff.2020 = sum(rt.trend.g[c(5:9)]*case[c(5:9)] - c.2020) + sum(rt.trend.g[c(10:24)]*case[c(10:24)]-c.2020.1)
case.diff.2025 = sum(rt.trend.g[c(10:14)]*case[c(10:14)] - c.2025) + sum(rt.trend.g[c(15:24)]*case[c(15:24)]-c.2025.1)
case.diff.2030 = sum(rt.trend.g[c(15:19)]*case[c(15:19)] - c.2030) + sum(rt.trend.g[c(20:24)]*case[c(20:24)]-c.2030.1)
CASE_SAVE = c(case.diff.2020, case.diff.2025, case.diff.2030)
data.frame(Intervention.YEAR,CASE_SAVE)
```

```{r}
in.cbp = 0.122622696
cbp.in.prescrip = ceiling(uti.inc*uti.ab*pop$Population[c(-1,-2)]*in.cbp*cbp.uti)

#inappropriate CBP prescription
red2020 = reduc*cbp.in.prescrip[4:8]
red2020.1 = rep(red2020[5],15)
red2025 = reduc*cbp.in.prescrip[9:13]
red2025.1 = rep(red2025[5],10)
red2030 = reduc*cbp.in.prescrip[14:18]
red2030.1 = rep(red2030[5],5)


plot(y = cbp.in.prescrip[3:24], x = c(2019:2040), ylim = range(0,red2020,cbp.in.prescrip),type = "l", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption per year", xlab = "Year")
par(new = T)
plot(y = c(cbp.in.prescrip[3:4], red2020, red2020.1), x = c(2019:2040), ylim = range(0,red2020,cbp.in.prescrip),type = "l", col = "blue", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption per year", xlab = "Year", lty = 2)
par(new = T)
plot(y = c(cbp.in.prescrip[3:9], red2025, red2025.1), x = c(2019:2040), ylim = range(0,red2020,cbp.in.prescrip),type = "l", col = "purple", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption per year", xlab = "Year", lty = 2)
par(new = T)
plot(y = c(cbp.in.prescrip[3:14], red2030, red2030.1), x = c(2019:2040), ylim = range(0,red2020,cbp.in.prescrip),type = "l", col = "red", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption per year", xlab = "Year", lty = 2)
axis(side=2, at=c(0, 20, 40, 60,80), hadj=0.8, cex.axis=0.9, las=2)
legend(2019, 30, legend = c("no stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.8, text.font=4, bg='lightblue')
```

MCMC for CI
```{r}
fit1 <- lm(log(1/uti.AB$freq -1) ~ c(0:12))
fit2 <- lm(log(1/rt.trend.g -1) ~ c(13:40))

conf.int <- predict(fit1, interval = "conf", newdata = data.frame(c(0:12)))
simreg1 <- function(mod = fit1){
  a = coef(mod)[1]
  b = coef(mod)[2]
  rse = summary(mod)$sigma
  x = c(0:40)
  y.sim <- rnorm(n = length(x), mean = a+b*x, sd = rse)
  lm.sim <- lm(y.sim ~ x)
  coef(lm.sim)
#ab.m = -b
#ab.rho = (ab.m-(ab.theta -1))/at
#ab.r0 = 1/(exp(a)+1)

#ab.rt <- exp((ab.rho*PA$consump+ab.theta-1)*t) / (1/ab.r0 -1 + #exp((ab.rho*PA$consump+ab.theta-1)*t))

  
}

#MC simulation
N <- 1000
simulated.coef <- replicate(N, simreg1())
simulated.coef <- t(simulated.coef)
sd(simulated.coef[,1])
sd(simulated.coef[,2])
summary(fit1)$coef[,1:2]
#MCMC CI for the slope
slop.ci <- quantile(simulated.coef[,2], c(0.025, 0.975))
#MCMC CI for the intercept
inter.ci <- quantile(simulated.coef[,1], c(0.025, 0.975))
#acutal intercept CI
confint(fit1)[1,]
#acutal slope CI
confint(fit1)[2,]


#rho CI
ab.m.l = -slop.ci[2]
ab.m.u = -slop.ci[1]
ab.rho.l = (ab.m.l-(ab.theta -1))/at
ab.rho.u = (ab.m.u-(ab.theta -1))/at
c(ab.rho.l, ab.rho.u)
#r0 CI
inter.ci.l = inter.ci[2]
inter.ci.u = inter.ci[1]
ab.r0.l = 1/(exp(inter.ci.l)+1)
ab.r0.u = 1/(exp(inter.ci.u)+1)
c(ab.r0.l, ab.r0.u)

m.trend.g.l <- ab.rho.l*c(consump.trend.g) + ab.theta -1
m.trend.g.u <- ab.rho.u*c(consump.trend.g) + ab.theta -1

rt.trend.g.l <- exp(m.trend.g.l*c(13:40)) / (1/ab.r0.l -1 + exp(m.trend.g.l*c(13:40)))
rt.trend.g.u <- exp(m.trend.g.u*c(13:40)) / (1/ab.r0.l -1 + exp(m.trend.g.u*c(13:40)))

data.frame(year = 2013:2040, lwr = rt.trend.g.l, upr = rt.trend.g.u)

#0:12 CI
rt.l <- uti.AB$freq - sqrt(PA$freq*(1-PA$freq)/PA$iso)
rt.u <- uti.AB$freq + sqrt(PA$freq*(1-PA$freq)/PA$iso)


plot(2000:2012, ylim = c(min(PA$freq), max(rt.trend.g)), xlim = range(2000:2040),y = PA$freq, xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", pch = 19, type = 'o', cex = 0.3)
lines(2013:2040, rt.trend.g.l, lty = 'dashed', col = 'red')
lines(2013:2040, rt.trend.g.u, lty = 'dashed', col = 'red')
polygon(c(2013:2040,rev(2013:2040)), c(rt.trend.g.l, rev(rt.trend.g.u)), col = 'grey80', border = NA)
par(new = T)
plot(2000:2040, ylim = c(min(PA$freq), max(rt.trend.g)),y = c(PA$freq,rt.trend.g), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship")
arrows(2000:2012, rt.l, 2000:2012, rt.u, length = 0.05, angle = 90, code = 3, col = "darkorange", pch = 5, cex = 3)
```