---
title: "PA_bac"
author: "Yiziying Chen"
output: html_document
---

```{r}
setwd( "/Users/yiziyingchen/Desktop/Townsend/Bac resist-Freq")
library("readxl")
BAC =  read_excel("Bac.xlsx", sheet = 1)
BAC$iso =BAC$`CDDEP Isolates_PA` + BAC$`MERCK Isolates_PA`
BAC$resis = BAC$Resistance_PA + BAC$Resistance_PA__1
BAC$freq = BAC$resis/BAC$iso
```



```{r, warning = FALSE}
t = seq(0,14,1)
in.pres = 0.136736215
d1 = c()
d2 = c()
c3 = c()
d4 = c()
d5 = c()
d.mean = c()
theta.m <- c()
set.seed(111)
for (i in 1:1000){
  d1 <- rnorm(18, 0.989, 0.006)
  d2 <- rnorm(18, 0.964, 0.008)
  d3 <- rnorm(18, 0.974, 0.013)
  d4 <- rnorm(18, 0.985, 0.005)
  d5 <- rnorm(18, 0.982, 0.007)
  d.mean <- (d1+d2+d3+d4+d5)/5
  theta.m <- c(theta.m, d.mean)
}
bac.theta <- mean(theta.m)

bac.k <- BAC$resis
bac.n <- BAC$iso
at <- sum(BAC$consump)/15
bac.at <- rep(at, 15)


```

```{r eval = FALSE, includ = F}
library(stats4)
#MLE for rho_hat--> is negative at this case , rt decreases then increase, and don't use it
logL<-function(r0, rho) {
  R<- dbinom(bac.k, bac.n, exp((rho*BAC$consump+bac.theta -1)*t)/(1/r0-1+exp((rho*BAC$consump + bac.theta-1)*t)))
  -sum(log(R))
}

result = mle(logL, start = list(r0 = BAC$freq[1], rho = 0))

bac.r01 = summary(result)@coef[1]
bac.rho1 = summary(result)@coef[2]

bac.rt1 <- exp((bac.rho1*BAC$consump+bac.theta -1)*t)/(1/bac.r01-1+exp((bac.rho1*BAC$consump + bac.theta-1)*t))
plot(bac.rt1, x = c(2000:2014), type = "l", main = "Bacteremia model r(t) projection", ylab = "rt", xlab = "Year")
bac.r01
bac.rt1

logL1<-function(r0, rho) -sum(dbinom(bac.k, size = bac.n, exp((rho*bac.at+bac.theta-1)*t)/(1/r0-1+exp((rho*bac.at + bac.theta-1)*t)),log=TRUE)) 
result1 = mle(logL1, start = list(r0 = BAC$freq[1], rho = 0.0001))
```

```{r include =F, eval = F}
#use optim
ll <- function(param){
  r0 = param[1]
  rho = param[2]
  #sum(log(dbinom(pa.k, pa.n, exp((rho*PA$consump+pa.theta -1)*t)/(1/r0-1+exp((rho*PA$consump + pa.theta-1)*t)))))
  R <- dbinom(bac.k,bac.n, exp((rho*BAC$consump+bac.theta -1)*t)/(1/r0-1+exp((rho*BAC$consump + bac.theta-1)*t)))
  sum(log(R))
}
bac.rho2 = optim(par = c(BAC$freq[1],0), ll)$par[2]

bac.r02 = optim(par = c(PA$freq[1],0), ll)$par[1]
bac.rt2 <- exp((bac.rho2*BAC$consump+bac.theta -1)*t)/(1/bac.r02-1+exp((bac.rho2*BAC$consump + bac.theta-1)*t))
cbind(bac.rho2, bac.r02)
plot(bac.rt2,  ylab = "r(t)", main = "Fitted r(t)",x = c(2000:2014),type = "l")
```

```{r warning = FALSE}
at <- sum(BAC$consump)/15
bac.at <- rep(at, 15)
fit1 <- lm(log(1/BAC$freq -1) ~ t)
inter <- summary(fit1)$coefficient[1]         
slope <- summary(fit1)$coefficient[2]         
bac.m = -slope
bac.rho = (bac.m-(bac.theta -1))/at
bac.r0 = 1/(exp(inter)+1)

bac.rt <- exp((bac.rho*BAC$consump+bac.theta-1)*t) / (1/bac.r0 -1 + exp((bac.rho*BAC$consump+bac.theta-1)*t))

#plot projected rt 2011-2014
library(calibrate)
names = as.factor(round(bac.rt,4))
plot((2000+t), bac.rt, type = "l", xlab = "Year", ylab = "Resistance Frequency", main = "Projection of Resistance Frequency from CPB prescription due to bacteremia")
data.frame(BAC$freq, bac.rt)
```


```{r}
consump <- lm(consump ~ t, data = BAC)
#2015 to 2019 projection
t1 <- seq(15,20,1)
consump.trend1 <- sapply(t1, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend1 <- bac.rho*consump.trend1 + bac.theta -1
rt.trend1 <- exp(m.trend1*t1) / (1/bac.r0 -1 + exp(m.trend1*t1))

#2020 to 2024 projection
t2 <- seq(21,25,1)
consump.trend2 <- sapply(t2, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend2 <- bac.rho*consump.trend2 + bac.theta-1
  ##without stewarship
  rt.trend2 <- exp(m.trend2*t2) / (1/bac.r0 -1 + exp(m.trend2*t2))
  ##with stewarship
  t2.1 <- c()
  c.trend2.1 <- c()
  rt.trend2.1 <- c()
  rt.t2.1<- c()
  for (i in 1:5){
    t2.1[i] <- (1-(0.52/5)*i)*consump.trend2[i]
    c.trend2.1 <- c(c.trend2.1, t2.1[i])
}
    m.trend2.1 <- bac.rho*c.trend2.1 + bac.theta -1
    rt.trend2.1 <- exp(m.trend2.1*t2) / (1/bac.r0 -1 + exp(m.trend2.1*t2))
    
t2.1<- seq(1,15,1)
consump.trend2.1.1 <-summary(consump)$coefficients[2]*t2.1 + c.trend2.1[5]
m.trend2.1.1 <- bac.rho*consump.trend2.1.1 + bac.theta -1
rt.trend2.1.1 <- exp(m.trend2.1.1 * c(26:40)) / (1/bac.r0-1 + exp(m.trend2.1.1*c(26:40)))


#2025 to 2030 projection
t3 <- seq(26,30,1)
consump.trend3 <- sapply(t3, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))

  ##without stewarship
  m.trend3 <- bac.rho*consump.trend3 + bac.theta -1
  rt.trend3 <- exp(m.trend3*(t3)) / (1/bac.r0 -1 + exp(m.trend3*t3))
  ##with stewarship
  t3.1 <- c()
  c.trend3.1 <- c()
  rt.trend3.1 <- c()
  rt.t3.1 <- c()
  for (i in 1:5){
    t3.1[i] <- (1-(0.52/5)*i)*consump.trend3[i]
    c.trend3.1 <- c(c.trend3.1, t3.1[i])
}
  m.trend3.1 <- bac.rho*c.trend3.1 + bac.theta -1 
  rt.trend3.1 <- exp(m.trend3.1*t3) / (1/bac.r0 -1 + exp(m.trend3.1*t3))

t3.1<- seq(1,10,1)
consump.trend3.1.1 <-summary(consump)$coefficients[2]*t3.1 + c.trend3.1[5]
m.trend3.1.1 <- bac.rho*consump.trend3.1.1 + bac.theta -1
rt.trend3.1.1 <- exp(m.trend3.1.1 * c(31:40)) / (1/bac.r0-1 + exp(m.trend3.1.1*c(31:40)))
  
#2035 to 2040 projection
t4 <- seq(31,35,1)
consump.trend4 <- sapply(t4, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
  ##without stwership
  m.trend4 <- bac.rho*consump.trend4 + bac.theta -1
  rt.trend4 <- exp(m.trend4*t4) / (1/bac.r0 -1 + exp(m.trend4*t4))
  ##with stwership 
  t4.1 <- c()
  c.trend4.1 <- c()
for (i in 1:5){
  t4.1[i] <- (1-(0.52/5)*i)*consump.trend4[i]
  c.trend4.1 <- c(c.trend4.1, t4.1[i])
}
  m.trend4.1 <- bac.rho*c.trend4.1 + bac.theta -1
  rt.trend4.1 <- exp(m.trend4.1*t4) / (1/bac.r0 -1 + exp(m.trend4.1*t4))

t4.1<- seq(1,5,1)
consump.trend4.1.1 <-summary(consump)$coefficients[2]*t4.1 + c.trend4.1[5]
m.trend4.1.1 <- bac.rho*consump.trend4.1.1 + bac.theta -1
rt.trend4.1.1 <- exp(m.trend4.1.1 * c(36:40)) / (1/bac.r0-1 + exp(m.trend4.1.1*c(36:40)))
  
#general without stewardship
t.g<- seq(15,40,1)
consump.trend.g<-sapply(t.g, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend.g <- bac.rho*consump.trend.g + bac.theta -1
rt.trend.g <- exp(m.trend.g*t.g) / (1/bac.r0 -1 + exp(m.trend.g*t.g))

```

```{r}
#plot overlay resisatnce frequency with/out intervension
plot(2000:2040, ylim = c(min(BAC$freq), max(rt.trend.g)),y = c(BAC$freq, rt.trend1, rt.trend2.1, rt.trend2.1.1), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "blue", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(BAC$freq), max(rt.trend.g)),y = c(BAC$freq, rt.trend1, rt.trend2, rt.trend3.1, rt.trend3.1.1), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "purple", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(BAC$freq), max(rt.trend.g)),y = c(BAC$freq, rt.trend1, rt.trend2, rt.trend3, rt.trend4.1, rt.trend4.1.1), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "red", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(BAC$freq), max(rt.trend.g)),y = c(BAC$freq,rt.trend.g), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship")

legend(2000, 0.8, legend = c("without stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.8, text.font=4, bg='lightblue')
```

```{r}
#Resistance frequency compare
library(scales)
rt.compare <- function(x1, x2) percent(((max(x1) - max(x2)) / max(x2)))
#2020 intervention
inter1 <- rt.compare(rt.trend2, rt.trend2.1)
#2025 intervention
inter2 <- rt.compare(rt.trend3, rt.trend3.1)
#2030 intervention
inter3<- rt.compare(rt.trend4, rt.trend4.1)
intervention <- c(2020,2025,2030)
#5-year RF change percentage with intervention
RF_diff <- c(inter1, inter2, inter3)
data.frame(intervention,RF_diff)
#5-year end point RF
END_RF = c(max(rt.trend2.1), max(rt.trend3.1), max(rt.trend4.1))
data.frame(intervention, END_RF)
```

```{r}
pop = read_excel("population.xlsx", sheet = 1)
pneu.pa = BAC$`bac-PA`[15]
cbp.bac = mean(BAC$`cbp-bac`)
bac.pa = mean(BAC$`bac-PA`)

#ratio of pneu contributed by PA should not be decreasing; take the last time point
in.cbp = 0.136736215
bac = 215.7
#pneu.pa =c()
#p1 = c()
#for(i in 15:40){
  #p1 = summary(m1)$coefficient[1] + summary(m1)$coefficient[2]*i
  #pneu.pa = c(pneu.pa,p1)
#}

#pneu.pa

case = c()
cn = c()
for(i in 15:40){
  cn = bac.pa*cbp.bac*pop$Population[(i-14)]*in.cbp*bac
  case = c(case,cn)
}

c25 = rt.trend.g[10]*case[10]
c25.1 = rt.trend2.1[5]*case[10]
int.2020 = c25 - c25.1
c30 = rt.trend.g[15]*case[15]
c30.1 = rt.trend3.1[5]*case[15]
int.2025 = c30 - c30.1
c35 = rt.trend.g[20]*case[20]
c35.1 = rt.trend4.1[5]*case[20]
int.2030 = c35 - c35.1
CASE.diff.10000PY = c(ceiling(int.2020), ceiling(int.2025), ceiling(int.2030))
YEAR = c(2020,2025,2030)

#5-year end point resistance cases number across US
END.CASE.100000PY <- ceiling(c(c25.1, c30.1, c35.1))
cbind(YEAR, END.CASE.100000PY)
#5-year isolate case number change under intervention in US
cbind(YEAR, CASE.diff.10000PY)

reduc = c()
for(i in 1:5)(reduc[i] = 1-(0.52/5)*i)
c.g1 <- case[1:6]*rt.trend.g[1:6]
c.g2 <- case[1:11]*rt.trend.g[1:11]
c.g3 <- case[1:16]*rt.trend.g[1:16]
c.2020 <- reduc*case[7:11]*rt.trend2.1
c.2020.1<- c.2020[5]+c(12:26)*summary(consump)$coefficients[2]
c.2025 <- reduc*case[12:16]*rt.trend3.1
c.2025.1<- c.2025[5]+c(17:26)*summary(consump)$coefficients[2]
c.2030 <- reduc*case[17:21]*rt.trend4.1
c.2030.1<- c.2030[5]+c(22:26)*summary(consump)$coefficients[2]



plot(case*rt.trend.g, x = c(2015:2040), type = "l", ylim = range(c.2020.1,case*rt.trend.g),main = "Resistance across US from CBP prescription due to Bacteremia", ylab = "Resistance Cases/100k PY", xlab = "Year")
par(new = T)
plot(c(c.g1, c.2020, c.2020.1), x = c(2015:2040), type = "l", ylim = range(c.2020.1, case*rt.trend.g), main = "Resistance across US from CBP prescription due to Bacteremia", ylab = "Resistance Cases/100k PY", xlab = "Year", col = "blue", lty = 2)
par(new = T)
plot(c(c.g2, c.2025, c.2025.1), x = c(2015:2040), type = "l", ylim = range(c.2020.1, case*rt.trend.g), main = "Resistance across US from CBP prescription due to Bacteremia", ylab = "Resistance Cases/100k PY", xlab = "Year", col = "purple", lty = 2)
par(new = T)
plot(c(c.g3, c.2030, c.2030.1), x = c(2015:2040), type = "l", ylim = range(c.2020.1, case*rt.trend.g), main = "Resistance across US from CBP prescription due to Bacteremia", ylab = "Resistance Cases/100k PY", xlab = "Year", col = "red", lty = 2)
legend(2015, 30000000, legend = c("without stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.8, text.font=4, bg='lightblue')

```

```{r}
cbp.in.prescrip = ceiling(bac*bac.pa*pop$Population*in.cbp*cbp.bac)

#inappropriate CBP prescription

  
red2020 = reduc*cbp.in.prescrip[7:11]
red2020.1 = red2020[5]+c(12:26)*summary(consump)$coefficients[2]
red2025 = reduc*cbp.in.prescrip[12:16]
red2025.1 = red2025[5]+c(17:26)*summary(consump)$coefficients[2]
red2030 = reduc*cbp.in.prescrip[17:21]
red2030.1 = red2030[5]+c(22:26)*summary(consump)$coefficients[2]

plot(y = cbp.in.prescrip, x = c(2015:2040), ylim = range(red2020,cbp.in.prescrip),type = "l", main = "Inappropriate CBP prescription for PA due to Bacteremia across US", ylab = "Inappropriate CBP prescirption/100k PY", xlab = "Year")
par(new = T)
plot(y = c(cbp.in.prescrip[1:6], red2020, red2020.1), x = c(2015:2040), ylim = range(red2020,cbp.in.prescrip),type = "l", col = "blue", main = "Inappropriate CBP prescription for PA due to Bacteremia across US", ylab = "Inappropriate CBP prescirption/100k PY", xlab = "Year", lty = 2)
par(new = T)
plot(y = c(cbp.in.prescrip[1:11], red2025, red2025.1), x = c(2015:2040), ylim = range(red2020,cbp.in.prescrip),type = "l", col = "purple", main = "Inappropriate CBP prescription for PA due to Bacteremia across US", ylab = "Inappropriate CBP prescirption/100k PY", xlab = "Year", lty = 2)
par(new = T)
plot(y = c(cbp.in.prescrip[1:16], red2030, red2030.1), x = c(2015:2040), ylim = range(red2020,cbp.in.prescrip),type = "l", col = "red", main = "Inappropriate CBP prescription for PA due to Bacteremia across US", ylab = "Inappropriate CBP prescirption/100k PY", xlab = "Year", lty = 2)
legend(2015, 250000, legend = c("no stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.7, text.font=4, bg='lightblue')
```

