---
title: "bac-PA2"
author: "Yiziying Chen"
date: "2/19/2019"
output: html_document
---

#data preparation
```{r warning=FALSE}
library(stats4)
setwd( "/Users/yiziyingchen/Desktop/Townsend/Bac resist-Freq")
library("readxl")
bac.PA =  read_excel("Bac2.xlsx", sheet = 1)
bac.PA$iso = bac.PA$`CDDEP Isolates_PA`+bac.PA$`MERCK Isolates_PA`
bac.PA$resis = bac.PA$Resistance_PA...3 + bac.PA$Resistance_PA...5
bac.PA$freq = bac.PA$resis/bac.PA$iso

t = seq(0,11,1)
bac.consump = bac.PA$Consumption

bac.d1 = c()
bac.d2 = c()
bac.c3 = c()
bac.d4 = c()
bac.d5 = c()
bac.d.mean = c()
bac.theta.m <- c()
set.seed(12345)
for (i in 1:1000){
  bac.d1 <- rnorm(1, 0.989, 0.006)
  bac.d2 <- rnorm(1, 0.964, 0.008)
  bac.d3 <- rnorm(1, 0.974, 0.013)
  bac.d4 <- rnorm(1, 0.985, 0.005)
  bac.d5 <- rnorm(1, 0.982, 0.007)
  bac.d.mean <- (bac.d1+bac.d2+bac.d3+bac.d4+bac.d5)/5
  bac.theta.m <- c(bac.theta.m, bac.d.mean)
}

#bac.pa.theta <- mean(bac.d1, bac.d2,bac.d3, bac.d4, bac.d5)
bac.pa.theta <- sort(bac.theta.m)[500]
bac.theta.l <- sort(bac.theta.m)[250]
bac.theta.u <- sort(bac.theta.m)[750]
bac.pa.theta <- sort(bac.theta.m)[500]
bac.pa.k <- bac.PA$resis
bac.pa.n <- bac.PA$iso
bac.a <- sum(bac.PA$Consumption)/12
bac.pa.a <- rep(bac.a, 12)
```


```{r eval = False}
#find rho value by assuming equal a(t) and fit linear regression
library(nlme)
bac.PA$iso1 = bac.PA$`MERCK Isolates_PA`
bac.PA$resis1 = bac.PA$Resistance_PA...5
bac.PA$freq1 = bac.PA$resis1/bac.PA$iso1
t = seq(0,11,1)
bac.at <- sum(bac.PA$Consumption)/12
freq.inv = 1/bac.PA$freq1
freq.inv[3] = freq.inv[2]
bac.fit2 <- lm(log(freq.inv -1) ~ t)
bac.inter1 <- summary(bac.fit2)$coefficient[1]         
bac.slope1 <- summary(bac.fit2)$coefficient[2]         
bac.pa.m1 = -bac.slope1
bac.pa.rho1 = (bac.pa.m1-(bac.pa.theta -1))/bac.a
bac.pa.r01 = 1/(exp(bac.inter1)+1)

bac.pa.rt1 <- exp((bac.pa.rho1*bac.PA$Consumption+bac.pa.theta-1)*t) / (1/bac.pa.r01 -1 + exp((bac.pa.rho1*bac.PA$Consumption+bac.pa.theta-1)*t))

#plot projected rt 2011-2014
library(calibrate)
cbind(bac.pa.rho1, bac.pa.r01)
plot((2000+t), bac.pa.rt1, type = "l", xlab = "Year", ylab = "Resistance Frequency", main = "Projection of Resistance Frequency from CPB prescription due to PA")
data.frame(bac.pa.rt1, bac.PA$freq)
```


##fitted generalized linear regression
```{r}
#find rho value by assuming equal a(t) and fit linear regression
library(nlme)
t = seq(0,11,1)
bac.at <- sum(bac.PA$Consumption)/12
bac.fit1 <- lm(log(1/bac.PA$freq -1) ~ t)
bac.inter <- summary(bac.fit1)$coefficient[1]         
bac.slope <- summary(bac.fit1)$coefficient[2]         
bac.pa.m = -bac.slope
bac.pa.rho = (bac.pa.m-(bac.pa.theta -1))/bac.a
bac.pa.r0 = 1/(exp(bac.inter)+1)

bac.pa.rt <- exp((bac.pa.rho*bac.PA$Consumption+bac.pa.theta-1)*t) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*bac.PA$Consumption+bac.pa.theta-1)*t))

#plot projected rt 2011-2014
library(calibrate)
cbind(bac.pa.rho, bac.pa.r0)
plot((2000+t), bac.pa.rt, type = "l", xlab = "Year", ylab = "Resistance Frequency", main = "Projection of Resistance Frequency from CPB prescription due to PA")
data.frame(bac.pa.rt, bac.PA$freq)
```

#general without stewardship
```{r}
bac.consump <- lm(Consumption ~ t, data = bac.PA)
bac.data <- data.frame(consump = bac.PA$Consumption, time = t)
bac.consump1 <- lm(consump ~ time, data = bac.data)
bac.conf.int <- predict(bac.consump1, interval = "conf", newdata = data.frame(time = c(12:45)))
bac.consump.l <- as.numeric(bac.conf.int[,2])
bac.consump.u <- as.numeric(bac.conf.int[,3])
bac.consump.g <- as.numeric(bac.conf.int[,1])

t.g<- seq(12,45,1)

#bac.consump.trend.g<-sapply(t.g, function(i) (summary(bac.consump)$coefficients[1] + i*summary(bac.consump)$coefficients[2]))
bac.rt.trend.g <- exp((bac.pa.rho*bac.consump.g + bac.pa.theta -1)*t.g) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*bac.consump.g + bac.pa.theta -1)*t.g))
bac.rt.trend.l <- exp((bac.pa.rho*bac.consump.l + bac.pa.theta.l -1)*t.g) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*bac.consump.l + bac.pa.theta.l -1)*t.g))

bac.rt.trend.u <- exp((bac.pa.rho*bac.consump.u + bac.pa.theta.u -1)*t.g) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*bac.consump.u + bac.pa.theta.u -1)*t.g))
bac.rt.trend.l
bac.rt.trend.g
bac.rt.trend.u
```

#without st
```{r}

t2 <- seq(26,30,1)
t3 <- seq(31,35,1)
t4 <- seq(36,40,1)

rt <- function(t_start,t_end, t){
  bac.m.trend <- bac.pa.rho*bac.consump.trend.g[t_start:t_end] + bac.pa.theta-1
  bac.rt.trend <- exp(bac.m.trend*t) / (1/bac.pa.r0 -1 + exp(bac.m.trend*t))
  return(bac.rt.trend)
}


bac.rt2025 <- rt(15,19,t2)
bac.rt2030 <- rt(20,24,t3)
bac.rt2030 <- rt(25,29,t4)
```

#with st
```{r}
bac.consump.trend <-c()
bac.c.trend <- c()
rt_st <- function(t_start, t_end, t){
  for (i in 1:5){
    bac.consump.trend[i] <- (1-(0.517/5)*i)*bac.consump.trend.g[i+t_start-12]
    bac.c.trend <- c(bac.c.trend, bac.consump.trend[i])
  }
  bac.m.trend <-  bac.pa.rho*bac.c.trend + bac.pa.theta -1
  bac.rt.trend <- exp(bac.m.trend*t) / (1/bac.pa.r0 -1 + exp(bac.m.trend*t))
  return(bac.rt.trend)
}

bac.rt2020st <- rt_st(21,25,t2)
bac.rt2025st <- rt_st(25,29,t3)
bac.rt2030st <- rt_st(30,34,t4)

```



```{r}
fit.data <- data.frame(resp = log(1/bac.PA$freq -1), time = c(0:11))
bac.fit1 <- lm(resp ~ time, data = fit.data)
predict(bac.fit1, interval = "conf", newdata = data.frame(time = c(12:45)))

```

```{r}
bac.rt.trend.l <- matrix(NA, ncol = 34, nrow = 1000)
bac.rt.trend.u <- matrix(NA, ncol = 34, nrow = 1000)
cons.l <- as.numeric(bac.conf.int[,2])
cons.u <- as.numeric(bac.conf.int[,3])

for (i in 1:1000){
  for (j in 1:34){
  bac.rt.trend.l[i,j] <- exp((bac.pa.rho*cons.l[j]+bac.theta.m[i]-1)*(j+11)) / (1/bac.pa.r01 -1 + exp((bac.pa.rho*cons.l[j]+bac.theta.m[i]-1)*(j+11)))
  bac.rt.trend.u[i,j] <- exp((bac.pa.rho*cons.u[j]+bac.theta.m[i]-1)*(j+11)) / (1/bac.pa.r01 -1 + exp((bac.pa.rho*cons.u[j]+bac.theta.m[i]-1)*(j+11)))
}
}

bac.rt.trend <- rbind(bac.rt.trend.l, bac.rt.trend.u)

for (i in 1:34){
  bac.rt.trend[,i] <- sort(bac.rt.trend[,i], decreasing = FALSE)
}

bac.rt.trend.l <- exp((bac.pa.rho*cons.l+bac.theta.l-1)*c(12:45)) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*cons.l+bac.theta.l-1)*c(12:45)))
bac.rt.trend.u <- exp((bac.pa.rho*cons.u+bac.theta.u-1)*c(12:45)) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*cons.u+bac.theta.u-1)*c(12:45)))
bac.rt.trend.g <- exp((bac.pa.rho*bac.consump.g+bac.pa.theta-1)*c(12:40)) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*bac.consump.g+bac.pa.theta-1)*c(12:45)))

bac.rt.trend.g <- exp((bac.pa.rho*bac.consump.g + bac.pa.theta -1)*c(12:45)) / (1/bac.pa.r0 -1 + exp((bac.pa.rho*bac.consump.g + bac.pa.theta -1)*c(12:45)))



bac.theta.l
bac.pa.theta
bac.theta.u

cons.l
bac.consump.trend.g
cons.u

bac.rt.l <- bac.rt.trend[250,]
bac.rt.u <- bac.rt.trend[170,]

bac.rt.l
bac.rt.u
bac.rt.trend.l
bac.rt.trend.u
bac.rt.trend.g
```



##MCMC inference for CI
```{r}
##resampling consump
bac.fit1 <- lm(log(1/bac.PA$freq -1) ~ c(0:11))
bac.fit2 <- lm(log(1/bac.rt.trend.g -1) ~ c(12:45))

resampled.consump <- matrix(NA, nrow = 1000, ncol = length(bac.consump.trend.g))
for (i in 1:1000){
  for (j in 1:length(bac.consump.trend.g)){
    resampled.consump[i,j] = rnorm(1,bac.consump.trend.g[j],1)
  }
}

for (i in 1:length(bac.consump.trend.g)){
  resampled.consump[,i] = sort(resampled.consump[,i])
}

bac.consump.l <- resampled.consump[250,]
bac.consump.u <- resampled.consump[750,]

##resampling theta
t.g <- c(12:45)
bac.m.l <- bac.pa.rho*cons.l + bac.theta.l -1
bac.rt.l <- exp(bac.m.l*t.g) / (1/bac.pa.r0 -1 + exp(bac.m.l*t.g))

bac.m.u <- bac.pa.rho*cons.u + bac.theta.u -1
bac.rt.u <- exp(bac.m.u*t.g) / (1/bac.pa.r0 -1 + exp(bac.m.u*t.g))


bacfreq.l <- exp((bac.pa.rho1*bac.PA$Consumption+bac.theta.l-1)*t) / (1/bac.pa.r01 -1 + exp((bac.pa.rho1*bac.PA$Consumption+bac.theta.l-1)*t))
bacfreq.u <- exp((bac.pa.rho1*bac.PA$Consumption+bac.theta.u-1)*t) / (1/bac.pa.r01 -1 + exp((bac.pa.rho1*bac.PA$Consumption+bac.theta.u-1)*t))

```





```{r}
##MCMC CI
rt.mcmc.l <- matrix(NA, ncol = 34, nrow = 1000)
rt.mcmc.u <- matrix(NA, ncol = 34, nrow = 1000)
for (i in 1:1000){
  for (j in 1:29){
      rt.mcmc.l[i,j] <- rnorm(1, bac.rt.l[j],1)
      rt.mcmc.u[i,j] <- rnorm(1, bac.rt.u[j],1)
  }
}

for (i in 1:29){
  rt.mcmc.l[,i] = sort(rt.mcmc.l[,i])
  rt.mcmc.u[,i] = sort(rt.mcmc.u[,i])
}

rt.mcmc.u[250,]
rt.mcmc.u[750,]

bac.conf.int <- predict(bac.fit1, interval = "conf", newdata = data.frame(c(0:11)))
bac.simreg1 <- function(mod = bac.fit1){
  a = coef(mod)[1]
  b = coef(mod)[2]
  rse = summary(mod)$sigma
  x = c(0:45)
  y.sim <- rnorm(n = length(x), mean = a+b*x, sd = rse)
  lm.sim <- lm(y.sim ~ x)
  coef(lm.sim)
#pa.m = -b
#pa.rho = (pa.m-(pa.theta -1))/at
#pa.r0 = 1/(exp(a)+1)

#pa.rt <- exp((pa.rho*PA$consump+pa.theta-1)*t) / (1/pa.r0 -1 + #exp((pa.rho*PA$consump+pa.theta-1)*t))
}

set.seed(12345)
bac.rt.all = c()
for(i in 1:12){
  bac.rt.sim <- rnorm(n = 1000, mean = bac.PA$freq, sd = summary(bac.fit1)$sigma)
  bac.rt.sim <- bac.rt.sim[order(bac.rt.sim)]
  bac.rt.all <- cbind(bac.rt.all, bac.rt.sim)
  bac.CI.l <- bac.rt.all[250,]
  bac.CI.u <- bac.rt.all[750,]
}

bacfreq.rt.l <- as.vector(bac.CI.l)
bacfreq.rt.u <- as.vector(bac.CI.u)


bac.rt.sim.2020 <- rnorm(n = 1000, mean = max(bac.rt2020st), sd = summary(bac.fit1)$sigma)
bac.rt.sim.2020 <- bac.rt.sim.2020[order(bac.rt.sim.2020)]
bac.rt.sim.2020[250]
bac.rt.sim.2020[750]

bac.rt.sim.2030 <- rnorm(n = 1000, mean = max(bac.rt2030st), sd = summary(bac.fit1)$sigma)
bac.rt.sim.2030 <- bac.rt.sim.2030[order(bac.rt.sim.2030)]
bac.rt.sim.2030[250]
bac.rt.sim.2030[750]

#MC simulation
N <- 1000
bac.simulated.coef <- replicate(N, bac.simreg1())
bac.simulated.coef <- t(bac.simulated.coef)
sd(bac.simulated.coef[,1])
sd(bac.simulated.coef[,2])
summary(bac.fit1)$coef[,1:2]
#MCMC CI for the slope
bac.slop.ci <- quantile(bac.simulated.coef[,2], c(0.025, 0.975))
#MCMC CI for the intercept
bac.inter.ci <- quantile(bac.simulated.coef[,1], c(0.025, 0.975))
#acutal intercept CI
confint(bac.fit1)[1,]
#acutal slope CI
confint(bac.fit1)[2,]


#rho CI
bac.pa.m.l = -bac.slop.ci[2]
bac.pa.m.u = -bac.slop.ci[1]
bac.pa.rho.l = (bac.pa.m.l-(bac.pa.theta.l -1))/bac.at
bac.pa.rho.u = (bac.pa.m.u-(bac.pa.theta.u -1))/bac.at
c(bac.pa.rho.l, bac.pa.rho.u)
#r0 CI
bac.inter.ci.l = bac.inter.ci[2]
bac.inter.ci.u = bac.inter.ci[1]
bac.pa.r0.l = 1/(exp(bac.inter.ci.l)+1)
bac.pa.r0.u = 1/(exp(bac.inter.ci.u)+1)
c(bac.pa.r0.l, bac.pa.r0.u)


bac.m.trend.g.l <- bac.pa.rho.l*c(bac.consump.trend.g) + bac.pa.theta.l -1
bac.m.trend.g.u <- bac.pa.rho.u*c(bac.consump.trend.g) + bac.pa.theta.u -1

bac.rt.trend.g.l <- exp(bac.m.trend.g.l*c(12:45)) / (1/bac.pa.r0.l -1 + exp(bac.m.trend.g.l*c(12:45)))
bac.rt.trend.g.u <- exp(bac.m.trend.g.u*c(12:45)) / (1/bac.pa.r0.l -1 + exp(bac.m.trend.g.u*c(12:45)))

data.frame(year = 2012:2040, lwr = bac.rt.trend.g.l, upr = bac.rt.trend.g.u, bac.rt.trend.g)


#0:12 CI
bacfreq.rt.l <- bac.PA$freq - 1.96*sqrt(bac.PA$freq*(1-bac.PA$freq)/bac.PA$iso)
bacfreq.rt.u <- bac.PA$freq + 1.96*sqrt(bac.PA$freq*(1-bac.PA$freq)/bac.PA$iso)

rt = matrix(nrow = 1000, ncol = 34)
for (i in 1:34){
  rt[,i] = rnorm(n = 1000, mean = bac.rt.trend.g.l[i], sd = summary(bac.fit1)$sigma)
  rt[,i] = sort(rt[,i])
}

rtl = rt[250,]
rtu = rt[750,]
#pa.rho.l = (pa.m.l-(bac.pa.theta -1))/at
#pa.rho.u = (pa.m.u-(bac.pa.theta -1))/at

#sd(simulated.coef[,1])
#sd(simulated.coef[,2])


#m.l <- pa.rho.l*at + bac.pa.theta -1
#m.u <- pa.rho.u*at + bac.pa.theta -1
#rt.l <- exp(m.l*c(0:12)) / (1/pa.r0.l -1 + exp(m.l*c(0:12)))
#rt.u <- exp(m.u*c(0:12)) / (1/pa.r0.u -1 + exp(m.u*c(0:12)))
```

##plot rt CI
```{r}
require(ggplot2)
require(plotrix)
require(grid)
require(gridExtra)
bac.dat <- data.frame(Year = 2000:2045, y = c(bac.PA$freq, bac.rt.trend.g[1:13], bac.rt2020st, rep(min(bac.rt2020st),15), bac.PA$freq, bac.rt.trend.g[1:18], bac.rt2025st, rep(min(bac.rt2025st),10), bac.PA$freq, bac.rt.trend.g[1:23], bac.rt2030st, rep(min(bac.rt2030st),5), bac.PA$freq, bac.rt.trend.g),  
                      lwr = rep(c(bacfreq.rt.l, rep(NA,34)),4), 
                      upr = rep(c(bacfreq.rt.u, rep(NA,34)),4),
                      l = rep(c(rep(NA,12),bac.rt.trend.l),4), 
                      u = rep(c(rep(NA,12),bac.rt.trend.u),4), 
                      Year.Start = factor(c(rep(2025,46), rep(2030,46), rep(2035,46), rep("none", 46))), 
                      Stewardship = factor(c(rep("with stewarship", 46*3), rep("no stewarship", 46))))

bac1 <- data.frame(Year = 2000:2011, y = bac.PA$freq, Stewardship = NA)
bac2 <- data.frame(Year = 2000:2045, y= c(bac.PA$freq,bac.rt.trend.g), Stewardship = NA)
bac3 <- data.frame(Year = 2012:2045, y= bac.rt.trend.g, Stewardship = NA)

p.bac <- ggplot(bac.dat, aes(x=Year, y=y, color=Year.Start)) + 
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("solid", "dotdash")) + scale_colour_manual(values=c("blue", "purple", "red", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("Resistance Frequency") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") + geom_errorbar(aes(ymin = lwr, ymax = upr), width = 0.4, color = "darkorange") + geom_ribbon(aes(ymin=l,ymax=u),alpha=0.2, fill = "blue",colour = NA) + theme_classic() + ylab("Resistance Frequency") + ggtitle("Bacteremia") + theme(plot.title =element_text(size=16, face="bold", hjust = 0.5), axis.title.y = element_text(size = 13), axis.title.x = element_text(size = 13), axis.text.x = element_text(size=13),axis.text.y = element_text(size=13))

jpeg(file="/Users/yiziyingchen/Desktop/Townsend/P.A./bac2_rt.jpeg",
width=500, height=400)

ggsave("bac2_rt.jpeg", width = 7, height = 5)
p.bac.plot2 <- p.bac + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")
```


#compare start vs. end rt
```{r}
#Resistance frequency compare
library(scales)
rt.compare <- function(x1, x2) percent(((max(x1) - min(x2)) / min(x2)))
#2020 intervention
bac.inter1 <- rt.compare(bac.rt2020, bac.rt2020st)
#2025 intervention
bac.inter2 <- rt.compare(bac.rt2025, bac.rt2025st)
#2030 intervention
bac.inter3<- rt.compare(bac.rt2030, bac.rt2030st)
intervention <- c(2020,2025,2030)
#5-year RF change percentage with intervention
bac.RF_diff <- c(bac.inter1, bac.inter2, bac.inter3)
data.frame(intervention,bac.RF_diff)
#5-year end point RF
bac.START_RF = c(max(bac.rt2020), max(bac.rt2025), max(bac.rt2030))
bac.END_RF = c(min(bac.rt2020st), min(bac.rt2025st), min(bac.rt2030st))
data.frame(intervention, bac.START_RF, bac.END_RF)

path = "/Users/yiziyingchen/Desktop/Townsend/P.A./"

library(openxlsx)
write.xlsx(data.frame(intervention, bac.START_RF, bac.END_RF), file =  paste0(path, "bac_rf.xlsx"), append = FALSE)
```



#resistance case difference-CROSS US
```{r}
pop = read_excel("population.xlsx", sheet = 1)
bac.pa = bac.PA$`bac-PA`[12]
cbp.bac = bac.PA$`cbp-bac`[12]
#ratio of pneu contributed by PA should not be decreasing; take the last time point
in.cbp = 0.136736215
##==1468/(1468+10736)
bac = 2.157*10^-3 #per Y
#pneu.pa =c()
#p1 = c()
#for(i in 15:40){
  #p1 = summary(m1)$coefficient[1] + summary(m1)$coefficient[2]*i
  #pneu.pa = c(pneu.pa,p1)
#}

#pneu.pa

bac.case = c()
bac.cn = c()
for(i in 19:40){
  bac.cn = bac.pa*cbp.bac*pop$Population[(i-14)]*bac
  bac.case = c(bac.case,bac.cn)
}
case = c()
case_reduc <- function(start, end){
  for (i in 1:5)
  case[i] <- (1-(0.517/5)*i)*bac.case[i+start-20]
  return(case)
}

bac.c25 = bac.rt.trend.g[13]*bac.case[6]
bac.c25.1 = bac.rt2020st[5]*case_reduc(21, 25)[5]
bac.int.2020 = bac.c25 - bac.c25.1
bac.c30 = bac.rt.trend.g[18]*bac.case[11]
bac.c30.1 = bac.rt2025st[5]*case_reduc(26, 30)[5]
bac.int.2025 = bac.c30 - bac.c30.1
bac.c35 = bac.rt.trend.g[23]*bac.case[16]
bac.c35.1 = bac.rt2030st[5]*case_reduc(31, 35)[5]
bac.int.2030 = bac.c35 - bac.c35.1
bac.CASE.diff = c(ceiling(bac.int.2020), ceiling(bac.int.2025), ceiling(bac.int.2030))
YEAR = c(2020,2025,2030)

#5-year end point resistance cases number across US
bac.END.CASE <- ceiling(c(bac.c25.1, bac.c30.1, bac.c35.1))
cbind(YEAR, bac.END.CASE)
bac.NO.STEWARD = c(bac.c25, bac.c30, bac.c35)
#5-year isolate case number change under intervention in US
cbind(YEAR, bac.CASE.diff)
cbind(YEAR, bac.NO.STEWARD)
data.frame(YEAR, bac.END.CASE, bac.NO.STEWARD)

write.xlsx(data.frame(YEAR, bac.END.CASE, bac.NO.STEWARD), file =  paste0(path, "bac_casecompare.xlsx"), append = FALSE)
```


```{r}
bac.c.g1 <- bac.case[1:2]*bac.rt.trend.g[7:8]
bac.c.g2 <- bac.case[1:7]*bac.rt.trend.g[7:13]
bac.c.g3 <- bac.case[1:12]*bac.rt.trend.g[7:18]
bac.c.2020 <- bac.case[3:7]*bac.rt2020st
bac.c.2020.1<- rep(bac.c.2020[5],15)
bac.c.2025 <- bac.case[8:12]*bac.rt2025st
bac.c.2025.1<- rep(bac.c.2025[5],10)
bac.c.2030 <- bac.case[13:17]*bac.rt2030st
bac.c.2030.1<- rep(bac.c.2030[5],5)
```

##Saved Cases
```{r}
bac.Intervention.YEAR = c(2020,2025,2030)
bac.case.diff.2020 = sum(bac.rt.trend.g[c(9:13)]*bac.case[c(2:6)] - bac.rt2020st*case_reduc(21, 25)) + sum(bac.rt.trend.g[c(14:28)]*bac.case[c(8:22)])-(bac.rt2020st[5]*case_reduc(21, 25)[5])*15
bac.case.diff.2025 = sum(bac.rt.trend.g[c(14:18)]*bac.case[c(7:11)] - bac.rt2025st*case_reduc(26, 30)) + sum(bac.rt.trend.g[c(19:28)]*bac.case[c(13:22)])-(bac.rt2025st[5]*case_reduc(26, 30)[5])*10
bac.case.diff.2030 = sum(bac.rt.trend.g[c(19:23)]*bac.case[c(12:16)] - bac.rt2030st*case_reduc(31, 35)) + sum(bac.rt.trend.g[c(24:28)]*bac.case[c(18:22)])-(bac.rt2030st[5]*case_reduc(31, 35)[5])*5
bac.CASE_SAVE = c(bac.case.diff.2020, bac.case.diff.2025, bac.case.diff.2030)
data.frame(bac.Intervention.YEAR,bac.CASE_SAVE)

write.xlsx(data.frame(bac.Intervention.YEAR, bac.CASE_SAVE), file = paste0(path, "bac_casesave.xlsx"), append = FALSE)
```

```{r}
plot((bac.case*bac.rt.trend.g[7:28]), x = c(2019:2040), ylim = range(0,2500), type = "l",main = "Resistance across US from CBP prescription due to Pneumonia", yaxt = "n",ylab = "Resistance per year", xlab = "Year")
par(new = T)
plot(c(bac.c.g1,bac.c.2020, bac.c.2020.1), x = c(2019:2040), type = "l", ylim = range(0,2500), main = "Resistance across US from CBP prescription due to Pneumonia", xlim = range(2019,2040),ylab = "Resistance per year", yaxt = "n", xlab = "Year", col = "blue", lty = 2)
par(new = T)
plot(c(bac.c.g2, bac.c.2025, bac.c.2025.1), x = c(2019:2040), type = "l", ylim = range(0,2500), main = "Resistance across US from CBP prescription due to Pneumonia", ylab = "Resistance per year", yaxt = "n", xlab = "Year", col = "purple", lty = 2)
par(new = T)
plot(c(bac.c.g3, bac.c.2030, bac.c.2030.1), x = c(2019:2040), type = "l", ylim = range(0,2500), main = "Resistance across US from CBP prescription due to Pneumonia", ylab = "Resistance per year", yaxt = "n", xlab = "Year", col = "red", lty = 2)
axis(side=2, hadj=0.8, cex.axis=0.9, las=2)
legend(2019, 2500, legend = c("without stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.8, text.font=4, bg='lightblue')
```

##ggplot CBP Prescription per Year
```{r}
bac.resis1 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g1,bac.c.2020, bac.c.2020.1), bac.case*bac.rt.trend.g[7:28]), Year.Start = factor(c(rep(2020,22), rep("baseline", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))))

bac.resis2 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g2, bac.c.2025, bac.c.2025.1),bac.case*bac.rt.trend.g[7:28]), Year.Start = factor(c(rep(2025,22), rep("baseline", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))))

bac.resis3 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g3, bac.c.2030, bac.c.2030.1),bac.case*bac.rt.trend.g[7:28]), Year.Start = factor(c(rep(2030,22), rep("baseline", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))))

bac.resis1 <- ggplot(bac.resis1, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("blue", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 2500))

bac.resis2 <- ggplot(bac.resis2, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c( "purple", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 2500))

bac.resis3 <- ggplot(bac.resis3, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("red", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 2500))

ggsave("bac_cbp_prescrip.jpeg", height = 5, width = 7)
bac.resis3 <- bac.resis3 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")
bac.resis1 <- bac.resis1 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")

bac.resis2 <- bac.resis2 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")
```


```{r}
bac.cbp.in.prescrip = ceiling(bac*bac.pa*pop$Population[c(-1,-2)]*in.cbp*cbp.bac)

#inappropriate CBP prescription
incase_reduc <- function(start, end){
  for (i in 1:5)
  case[i] <- (1-(0.517/5)*i)*bac.cbp.in.prescrip[i+start-20]
  return(case)
}
bac.red2020 = incase_reduc(21,25)
bac.red2020.1 = rep(bac.red2020[5],15)
bac.red2025 = incase_reduc(26,30)
bac.red2025.1 = rep(bac.red2025[5],10)
bac.red2030 = incase_reduc(31,35)
bac.red2030.1 = rep(bac.red2030[5],5)
```

```{r}
plot(y = bac.cbp.in.prescrip[3:24], x = c(2019:2040), ylim = range(0,bac.red2020,bac.cbp.in.prescrip),type = "l", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption per year", xlab = "Year")
par(new = T)
plot(y = c(bac.cbp.in.prescrip[3:4], bac.red2020, bac.red2020.1), x = c(2019:2040), ylim = range(0,bac.red2020,bac.cbp.in.prescrip),type = "l", col = "blue", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption per year", xlab = "Year", lty = 2)
par(new = T)
plot(y = c(bac.cbp.in.prescrip[3:9], bac.red2025, bac.red2025.1), x = c(2019:2040), ylim = range(0,bac.red2020,bac.cbp.in.prescrip),type = "l", col = "purple", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption per year", xlab = "Year", lty = 2)
par(new = T)
plot(y = c(bac.cbp.in.prescrip[3:14], bac.red2030, bac.red2030.1), x = c(2019:2040), ylim = range(0,bac.red2020,bac.cbp.in.prescrip),type = "l", col = "red", main = "Inappropriate CBP prescription projection across US", yaxt = "n", ylab = "Inappropriate CBP prescirption \n per year", xlab = "Year", lty = 2)
axis(side=2, at=c(0, 100, 200, 300, 400,500,600),hadj=0.9, cex.axis=0.8, las=2)
legend(2020, 150, legend = c("no stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.8, text.font=4, bg='lightblue')
```


```{r}
p.bac1 <- data.frame(Year = 2019:2040, y = c(c(bac.cbp.in.prescrip[3:4], bac.red2020, bac.red2020.1), bac.cbp.in.prescrip[3:24]), Year.Start = factor(c(rep(2020,22),  rep("non", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))),u = rep(bac.cbp.in.prescrip[3:24],2))

p.bac2 <- data.frame(Year = 2019:2040, y = c(c(bac.cbp.in.prescrip[3:9], bac.red2025, bac.red2025.1), bac.cbp.in.prescrip[3:24]), Year.Start = factor(c( rep(2025,22), rep("non", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))),u = rep(bac.cbp.in.prescrip[3:24],2))

p.bac3 <- data.frame(Year = rep(2019:2040,2), y = c(c(bac.cbp.in.prescrip[3:14], bac.red2030, bac.red2030.1), bac.cbp.in.prescrip[3:24]), Year.Start = factor(c(rep(2030,22), rep("non", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))), u = rep(bac.cbp.in.prescrip[3:24],2))

bac.bac1 <- subset(p.bac1,Year.Start == "2020")
bac.bac2 <- subset(p.bac2,Year.Start == "2025")
bac.bac3 <- subset(p.bac3,Year.Start == "2030")

p.bac.pres1 <- ggplot(p.bac1, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("blue", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("Inappropriate CBP prescirption \n per year") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") +scale_y_continuous(limits=c(0, 2500)) + geom_ribbon(data=bac.bac1, aes(ymin =y, ymax =u), alpha = 0.2, fill = "blue", colour = NA)

p.bac.pres2 <- ggplot(p.bac2, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("purple", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("Inappropriate CBP prescirption \n per year") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") +scale_y_continuous(limits=c(0, 2500)) + geom_ribbon(data = bac.bac2, aes(ymin =y, ymax =u), alpha = 0.2, fill = "purple", colour = NA) 

p.bac.pres3 <- ggplot(p.bac3, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("red", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("Inappropriate CBP prescirption \n per year") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") +scale_y_continuous(limits=c(0, 2500)) + geom_ribbon(data = bac.bac3, aes(ymin =y, ymax =u), alpha = 0.2, fill = "red", colour = NA)

ggsave("bac_in.pres2.jpeg", height = 5, width = 7)
p.bac.pres2 <- p.bac.pres2 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")
p.bac.pres1 <- p.bac.pres1 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")
p.bac.pres3 <- p.bac.pres3 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")

bac.resis1 + p.bac.pres1
```

##ggplot CBP Prescription per Year
```{r}
bac.resis1 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g1,bac.c.2020, bac.c.2020.1), bac.case*bac.rt.trend.g[7:28]), Year.Start = factor(c(rep(2020,22), rep("baseline", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))))

bac.resis2 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g2, bac.c.2025, bac.c.2025.1),bac.case*bac.rt.trend.g[7:28]), Year.Start = factor(c(rep(2025,22), rep("baseline", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))))

bac.resis3 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g3, bac.c.2030, bac.c.2030.1),bac.case*bac.rt.trend.g[7:28]), Year.Start = factor(c(rep(2030,22), rep("baseline", 22))), Stewardship = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))))

bac.resis1 <- ggplot(bac.resis1, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("blue", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 2500))

bac.resis2 <- ggplot(bac.resis2, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c( "purple", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 2500))

bac.resis3 <- ggplot(bac.resis3, aes(x=Year, y=y, color=Year.Start)) +
geom_line(aes(linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("red", "black"))+ theme(legend.position = "none") +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 2500))

ggsave("bac_cbp_prescrip.jpeg", height = 5, width = 7)
bac.resis3 <- bac.resis3 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")
bac.resis1 <- bac.resis1 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")

bac.resis2 <- bac.resis2 + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")
```



```{r}
bac.resis1 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g1,bac.c.2020, bac.c.2020.1), bac.case*bac.rt.trend.g[7:28]), Stewardship = factor(c(rep(2020,22), rep("status quo", 22))), start.year = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))), u = NA, type = rep("overall prescription", 22))



p.bac1 <- data.frame(Year = 2019:2040, y = c(c(bac.cbp.in.prescrip[3:4], bac.red2020, bac.red2020.1), bac.cbp.in.prescrip[3:24]), Stewardship = factor(c(rep(2020,22),  rep("status quo", 22))), start.year = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))), u = rep(bac.cbp.in.prescrip[3:24],2), type = rep("inappropriate prescription", 22))

bac.bac1 <- subset(p.bac1,Stewardship == "2020")

bac.prescrip_in1 <- ggplot() + geom_line(bac.resis1, mapping = aes(x=Year, y=y, color=Stewardship, linetype = Stewardship))+ geom_line(p.bac1, mapping = aes(x=Year, y=y, color=Stewardship, linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_color_manual(values=c("blue", "black"))+ scale_fill_manual(name="Prescription Type",values= c("inappriopriate prescription" = "lightblue")) +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia")  + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 3000)) + geom_ribbon(data=bac.bac1, aes(x = Year, ymin =y, ymax =u), alpha = 0.2, fill = "blue", colour = NA) + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")



bac.resis2 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g2, bac.c.2025, bac.c.2025.1),bac.case*bac.rt.trend.g[7:28]), Stewardship = factor(c(rep(2025,22), rep("status quo", 22))), start.year = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))), u = NA,type = rep("overall prescription", 22))

p.bac2 <- data.frame(Year = 2019:2040, y = c(c(bac.cbp.in.prescrip[3:9], bac.red2025, bac.red2025.1), bac.cbp.in.prescrip[3:24]), Stewardship = factor(c( rep(2025,22), rep("status quo", 22))), start.year = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))),u = rep(bac.cbp.in.prescrip[3:24],2), type = rep("inappropriate prescription", 22))

bac.bac2 <- subset(p.bac2,Stewardship == "2025")

bac.prescrip_in2 <- ggplot() + geom_line(bac.resis2, mapping = aes(x=Year, y=y, color=Stewardship, linetype = Stewardship))+ geom_line(p.bac2, mapping = aes(x=Year, y=y, color=Stewardship, linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_colour_manual(values=c("purple", "black"))+scale_fill_manual(name="Prescription Type",values= c("inappriopriate prescription" = "purple")) + theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 3000)) + geom_ribbon(data=bac.bac2, aes(x = Year, ymin =y, ymax =u), alpha = 0.2, fill = "purple", colour = NA) + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")

#+ theme(legend.position ="bottom", axis.text=element_text(size=14), axis.title=element_text(size=14,face="bold")) 

bac.resis3 <- data.frame(Year = 2019:2040, y = c(c(bac.c.g3, bac.c.2030, bac.c.2030.1),bac.case*bac.rt.trend.g[7:28]), Stewardship = factor(c(rep(2030,22), rep("status quo", 22))), start.year = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))), u = NA,type = rep("overall prescription", 22))

p.bac3 <- data.frame(Year =2019:2040, y = c(c(bac.cbp.in.prescrip[3:14], bac.red2030, bac.red2030.1), bac.cbp.in.prescrip[3:24]), Stewardship = factor(c(rep(2030,22), rep("status quo", 22))), start.year = factor(c(rep("with stewarship", 22), rep("without stewarship", 22))), u = rep(bac.cbp.in.prescrip[3:24],2), type = rep("inappropriate prescription", 22))

bac.bac3 <- subset(p.bac3,Stewardship == "2030")

bac.prescrip_in3 <- ggplot() + geom_line(bac.resis3, mapping = aes(x=Year, y=y, color=Stewardship, linetype = Stewardship))+ geom_line(p.bac3, mapping = aes(x=Year, y=y, color=Stewardship, linetype = Stewardship)) + scale_linetype_manual(values=c("dotdash", "solid")) + scale_color_manual(values=c("red", "black"))+ scale_fill_manual(name="Prescription Type",values= c("inappriopriate prescription" = "red")) +  theme_classic() + ylab("CBP prescription \n per year for Bacteremia") + ggtitle("Bacteremia") + scale_y_continuous(limits=c(0, 3000)) + geom_ribbon(data=bac.bac3, aes(x = Year, ymin =y, ymax =u), alpha = 0.2, fill = "red", colour = NA) + theme(plot.title =element_text(size=18, face="bold", hjust = 0.5), legend.position ="none")

```



```{r}
plot(2000:2011, ylim = c(min(bac.PA$freq), max(bac.rt.trend.g)), xlim = range(2000:2040),y = bac.PA$freq, xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", pch = 19, type = 'o', cex = 0.3)
arrows(2000:2011, bac.rt.l, 2000:2011, bac.rt.u, length = 0.03, angle = 90, code = 3, col = "darkorange", pch = 5, cex = 3)
lines(2012:2040, bac.rt.trend.g.l, lty = 'dashed', col = 'red')
lines(2012:2040, bac.rt.trend.g.u, lty = 'dashed', col = 'red')
polygon(c(2012:2040,rev(2012:2040)), c(bac.rt.trend.g.l, rev(bac.rt.trend.g.u)), col = 'grey80', border = NA)
par(new = T)
plot(2000:2040, ylim = c(min(bac.PA$freq), max(bac.rt.trend.g)),y = c(bac.PA$freq,bac.rt.trend.g), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship")
```

#ggplot for MCMC CI
```{r}
bac1 <- data.frame(Year = 2000:2011, y = bac.PA$freq, Stewardship = NA)
bac2 <- data.frame(Year = 2000:2040, y= c(bac.PA$freq,bac.rt.trend.g), Stewardship = NA)
bac3 <- data.frame(Year = 2012:2040, y= bac.rt.trend.g, Stewardship = NA)
bac4 <- data.frame(Year = 2000:2011, y = bacfreq.rt.l, Stewardship = bacfreq.rt.u)

ggsave("ci.bac.jpeg", height = 5, width = 7)
ci.bac <- ggplot(bac2, aes(x=Year, y=y)) + geom_line() + geom_point(data = bac1, size = 0.8) + geom_errorbar(data = bac1, aes(ymin = lwr, ymax = upr), width = 0.4, color = "darkorange") + geom_ribbon(data=bac3,aes(ymin=lwr,ymax=upr),alpha=0.2, fill = "blue") + theme_classic() + ylab("Resistance Frequency") + ggtitle("Bacteremia") + theme(plot.title =element_text(size=16, face="bold", hjust = 0.5), axis.title.y = element_text(size = 13), axis.title.x = element_text(size = 13), axis.text.x = element_text(size=13),axis.text.y = element_text(size=13))

length(bac.rt.l)
```

```{r}
summary = summary(lm(bac.PA$freq ~ bac.PA$Year))

summary$coefficient[1] + summary$coefficient[2]*2020
summary$coefficient[1] + summary$coefficient[2]*2040

```

```{r eval = FALSE}
#use optim
ll <- function(param){
  r0 = param[1]
  rho = param[2]
  #sum(log(dbinom(pa.k, pa.n, exp((rho*PA$Consumption+pa.theta -1)*t)/(1/r0-1+exp((rho*PA$Consumption + pa.theta-1)*t)))))
  R <- dbinom(bac.pa.k, bac.pa.n, exp((rho*bac.at*bac.PA$freq+bac.pa.theta -1)*t)/(1/r0-1+exp((rho*bac.at*bac.PA$freq + bac.pa.theta-1)*t)))
  -sum(log(R))
}
pa.rho2 = optim(par = c(bac.PA$freq[1],0), ll)$par[2]

pa.r02 = optim(par = c(bac.PA$freq[1],0), ll)$par[1]
pa.rt2 <- exp((pa.rho2*bac.at*bac.PA$freq+bac.pa.theta -1)*t)/(1/pa.r02-1+exp((pa.rho2*bac.at*bac.PA$freq + bac.pa.theta-1)*t))
cbind(pa.rho2, pa.r02)
plot(pa.rt2,  ylab = "r(t)", main = "Fitted r(t)",x = c(2000:2011),type = "l", ylim = c(0.1, 0.2))
par(new = T)
plot(pneu.PA$freq,  ylab = "r(t)", main = "Fitted r(t)",x = c(2000:2011),type = "l", ylim = c(0.1, 0.2), col = "blue")
```


