---
title: "cIAI-KP"
author: "Yiziying Chen"
date: "2/28/2019"
output: html_document
---

```{r warning=FALSE}
library(stats4)
setwd( "/Users/yiziyingchen/Desktop/Townsend/IAI")
library("readxl")
iai.KP =  read_excel("IAI.xlsx", sheet = 3)
iai.KP$iso = iai.KP$Isolates_KP
iai.KP$resis = iai.KP$Resistance_KP
iai.KP$freq = iai.KP$resis/KP$iso

t = seq(0,16,1)

d1 = c()
d2 = c()
c3 = c()
d4 = c()
d5 = c()
d.mean = c()
theta.m <- c()
set.seed(111)
for (i in 1:1000){
  d1 <- rnorm(18, 0.989, 0.006)
  d2 <- rnorm(18, 0.964, 0.008)
  d3 <- rnorm(18, 0.974, 0.013)
  d4 <- rnorm(18, 0.985, 0.005)
  d5 <- rnorm(18, 0.982, 0.007)
  d.mean <- (d1+d2+d3+d4+d5)/5
  theta.m <- c(theta.m, d.mean)
}
kp.theta <- mean(theta.m)

kp.k <- iai.KP$resis
kp.n <-iai.KP$iso
at <- sum(iai.KP$consump)/17
kp.at <- rep(at, 17)
```

```{r eval = FALSE}
#use optim
ll <- function(param){
  r0 = param[1]
  rho = param[2]
  #sum(log(dbinom(pa.k, pa.n, exp((rho*PA$consump+pa.theta -1)*t)/(1/r0-1+exp((rho*PA$consump + pa.theta-1)*t)))))
  R <- dbinom(kp.k, kp.n, exp((rho*iai.KP$consump+kp.theta -1)*t)/(1/r0-1+exp((rho*iai.KP$consump + kp.theta-1)*t)))
  -sum(log(R))
}
kp.rho = optim(par = c(0.0005,0), ll)$par[2]

kp.r0 = optim(par = c(0.0005,0), ll)$par[1]
kp.rt <- exp((kp.rho*iai.KP$consump+kp.theta -1)*t)/(1/kp.r0-1+exp((kp.rho*iai.KP$consump + kp.theta-1)*t))
cbind(kp.rho, kp.r0)
plot(kp.rt,  ylab = "r(t)", x = c(2000:2016),type = "l",main = "Projection of Resistance Frequency from CPB prescription due to PA")
data.frame(kp.rt, KP$freq)
```

```{r}
consump <- lm(consump ~ t, data = KP)
#2015 to 2019 projection
t1 <- seq(17,20,1)
consump.trend1 <- sapply(t1, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend1 <- kp.rho*consump.trend1 + kp.theta -1
rt.trend1 <- exp(m.trend1*t1) / (1/kp.r0 -1 + exp(m.trend1*t1))

#2020 to 2024 projection
t2 <- seq(21,25,1)
consump.trend2 <- sapply(t2, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend2 <- kp.rho*consump.trend2 + kp.theta-1
  ##without stewarship
  rt.trend2 <- exp(m.trend2*t2) / (1/kp.r0 -1 + exp(m.trend2*t2))
  ##with stewarship
  t2.1 <- c()
  c.trend2.1 <- c()
  rt.trend2.1 <- c()
  rt.t2.1<- c()
  for (i in 1:5){
    t2.1[i] <- (1-(0.52/5)*i)*consump.trend2[1]
    c.trend2.1 <- c(c.trend2.1, t2.1[i])
}
    m.trend2.1 <- kp.rho*c.trend2.1 + kp.theta -1
    rt.trend2.1 <- exp(m.trend2.1*t2) / (1/kp.r0 -1 + exp(m.trend2.1*t2))

t2.1<- seq(1,15,1)
consump.trend2.1.1 <-summary(consump)$coefficients[2]*t2.1 + c.trend2.1[5]
m.trend2.1.1 <- kp.rho*consump.trend2.1.1 + kp.theta -1
rt.trend2.1.1 <- exp(m.trend2.1.1 * c(26:40)) / (1/kp.r0-1 + exp(m.trend2.1.1*c(26:40)))


#2025 to 2030 projection
t3 <- seq(26,30,1)
consump.trend3 <- sapply(t3, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))

  ##without stewarship
  m.trend3 <- kp.rho*consump.trend3 + kp.theta -1
  rt.trend3 <- exp(m.trend3*(t3)) / (1/kp.r0 -1 + exp(m.trend3*t3))
  ##with stewarship
  t3.1 <- c()
  c.trend3.1 <- c()
  rt.trend3.1 <- c()
  rt.t3.1 <- c()
  for (i in 1:5){
    t3.1[i] <- (1-(0.52/5)*i)*consump.trend3[1]
    c.trend3.1 <- c(c.trend3.1, t3.1[i])
}
  m.trend3.1 <- kp.rho*c.trend3.1 + kp.theta -1 
  rt.trend3.1 <- exp(m.trend3.1*t3) / (1/kp.r0 -1 + exp(m.trend3.1*t3))
  
t3.1<- seq(1,10,1)
consump.trend3.1.1 <-summary(consump)$coefficients[2]*t3.1 + c.trend3.1[5]
m.trend3.1.1 <- kp.rho*consump.trend3.1.1 + kp.theta -1
rt.trend3.1.1 <- exp(m.trend3.1.1 * c(31:40)) / (1/kp.r0-1 + exp(m.trend3.1.1*c(31:40)))

#2035 to 2040 projection
t4 <- seq(31,35,1)
consump.trend4 <- sapply(t4, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
  ##without stwership
  m.trend4 <- kp.rho*consump.trend4 + kp.theta -1
  rt.trend4 <- exp(m.trend4*t4) / (1/kp.r0 -1 + exp(m.trend4*t4))
  ##with stwership 
  t4.1 <- c()
  c.trend4.1 <- c()
for (i in 1:5){
  t4.1[i] <- (1-(0.52/5)*i)*consump.trend4[1]
  c.trend4.1 <- c(c.trend4.1, t4.1[i])
}
  m.trend4.1 <- kp.rho*c.trend4.1 + kp.theta -1
  rt.trend4.1 <- exp(m.trend4.1*t4) / (1/kp.r0 -1 + exp(m.trend4.1*t4))

t4.1<- seq(1,5,1)
consump.trend4.1.1 <-summary(consump)$coefficients[2]*t4.1 + c.trend4.1[5]
m.trend4.1.1 <- kp.rho*consump.trend4.1.1 + kp.theta -1
rt.trend4.1.1 <- exp(m.trend4.1.1 * c(36:40)) / (1/kp.r0-1 + exp(m.trend4.1.1*c(36:40)))  
  
#general without stewardship
t.g<- seq(17,40,1)
consump.trend.g<-sapply(t.g, function(i) (summary(consump)$coefficients[1] + i*summary(consump)$coefficients[2]))
m.trend.g <- kp.rho*consump.trend.g + kp.theta -1
rt.trend.g <- exp(m.trend.g*t.g) / (1/kp.r0 -1 + exp(m.trend.g*t.g))

```

```{r}
#plot overlay resisatnce frequency with/out intervension
plot(2000:2040, ylim = c(min(KP$freq), max(rt.trend.g)),y = c(KP$freq, rt.trend1, rt.trend2.1, rep(rt.trend2.1[5],15)), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "blue", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(KP$freq), max(rt.trend.g)),y = c(KP$freq, rt.trend1, rt.trend2, rt.trend3.1, rep(rt.trend3.1[5],10)), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "purple", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(KP$freq), max(rt.trend.g)),y = c(KP$freq, rt.trend1, rt.trend2, rt.trend3, rt.trend4.1, rep(rt.trend4.1[5],5)), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship", col = "red", lty = 2)
par(new = T)
plot(2000:2040, ylim = c(min(KP$freq), max(rt.trend.g)),y = c(KP$freq,rt.trend.g), type = "l", xlab = "Year", ylab = "Resistance Frequency",main = "Projected Resistance Frequency with/out Bacteria Stewardship")
#text(c(2000:2040), c(ab.rt,rt.trend.g), round(c(ab.rt,rt.trend.g),2),cex=0.75, col = "dark orange")

legend(2000, 0.6, legend = c("without stewardship", "2020", "2025", "2030"), col = c("black", "blue", "purple", "red"), lty = c(1,2,2,2),cex=0.8, text.font=4, bg='lightblue')
```

```{r}
#Resistance frequency compare
library(scales)
rt.compare <- function(x1, x2) percent(((max(x1) - min(x2)) / min(x2)))
#2020 intervention
inter1 <- rt.compare(rt.trend2, rt.trend2.1)
#2025 intervention
inter2 <- rt.compare(rt.trend3, rt.trend3.1)
#2030 intervention
inter3<- rt.compare(rt.trend4, rt.trend4.1)
intervention <- c(2020,2025,2030)
#5-year RF change percentage with intervention
RF_diff <- c(inter1, inter2, inter3)
data.frame(intervention,RF_diff)
#5-year end point RF
END_RF = c(max(rt.trend2.1), max(rt.trend3.1), max(rt.trend4.1))
data.frame(intervention, END_RF)
```

#resistance case difference-CROSS US
```{r}
pop = read_excel("population.xlsx", sheet = 1)
iai.kp = iai.KP$`cIAI - KP`
cbp.iai = mean(iai.KP$`CBP-cIAI`)
#ratio of iai contributed by PA should not be decreasing; take the last time point
in.cbp = 0.136736215
iai = 3*10^-3
#iai.pa =c()
#p1 = c()
#for(i in 15:40){
  #p1 = summary(m1)$coefficient[1] + summary(m1)$coefficient[2]*i
  #iai.pa = c(iai.pa,p1)
#}

#iai.pa

case = c()
cn = c()
for(i in 17:40){
  cn = iai.kp*cbp.iai*pop$Population[(i-14)]*in.cbp*iai
  case = c(case,cn)
}

c25 = rt.trend.g[9]*case[9]
c25.1 = rt.trend2.1[5]*case[9]
int.2020 = c25 - c25.1
c30 = rt.trend.g[14]*case[14]
c30.1 = rt.trend3.1[5]*case[14]
int.2025 = c30 - c30.1
c35 = rt.trend.g[19]*case[19]
c35.1 = rt.trend4.1[5]*case[19]
int.2030 = c35 - c35.1
CASE.diff = c(ceiling(int.2020), ceiling(int.2025), ceiling(int.2030))
YEAR = c(2020,2025,2030)

#5-year end point resistance cases number across US
END.CASE <- ceiling(c(c25.1, c30.1, c35.1))
cbind(YEAR, END.CASE)
NO.STEWARD = c(c25, c30, c35)
#5-year isolate case number change under intervention in US
cbind(YEAR, CASE.diff)
cbind(YEAR, NO.STEWARD)
```

